<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LOKGKB2" failures="1" tests="7" name="ChromeTest" time="98.099" errors="0" timestamp="2025-09-02T17:43:49 IST">
  <testcase classname="com.OpenCart.TestCases.T2_LoginPageTest" name="varifyUrl" time="0.063"/>
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyProductCount" time="0.039"/>
  <testcase classname="com.OpenCart.TestCases.T2_LoginPageTest" name="varifyTitle" time="0.013"/>
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyProductDetails" time="0.155"/>
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="validateAddToCart" time="26.46"/>
  <testcase classname="com.OpenCart.TestCases.T2_LoginPageTest" name="validateLoginFunctionality" time="1.063">
    <failure type="java.lang.AssertionError" message="Login Fail! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail! expected [true] but found [false]
at com.OpenCart.TestCases.T2_LoginPageTest.validateLoginFunctionality(T2_LoginPageTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginFunctionality -->
  <testcase classname="com.OpenCart.TestCases.T3_HomePageTest" name="verifyCartPageLaunch" time="0.169"/>
</testsuite> <!-- ChromeTest -->
